version: '3.8'

services:
  # 1. PostgreSQL Database
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=postgres
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Healthcheck to ensure database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Config Server
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - my-network
    healthcheck:
      test: "curl -f http://localhost:8888/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # 3. Service Discovery
  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - my-network
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

    healthcheck:
      test: "curl -f http://localhost:8761/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 4. User Backend
  user-backend:
    build: ./user-backend
    container_name: user-backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      postgres-db:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres-db:5432/postgres
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/

  # 5. API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    networks:
      - my-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/

# Common network
networks:
  my-network:
    driver: bridge

# Database data volume
volumes:
  postgres_data:
    driver: local