
name: CI for order Service


on:
  push:
    branches:
      - master  
    paths:
      - 'order-service/**' 


jobs:
  build-and-push-image:
   
    runs-on: ubuntu-latest

  
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest 

 
  deploy:
    runs-on: self-hosted
    needs: build-and-push-image
    steps:
      - name: Deploy to Production Server
        run: |
          cd /home/ankur/Desktop/microservices
          git pull
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker compose up -d --no-deps order-service