
name: CI for User Backend


on:
  push:
    branches:
      - master  # Jab bhi 'main' branch par push hoga
    paths:
      - 'user-backend/**' 


jobs:
  build-and-push-image:
   
    runs-on: ubuntu-latest

  
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./user-backend  
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-backend:latest 